src/Entity/Inventaire.php
<?php

namespace App\Entity;

use App\Repository\InventaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InventaireRepository::class)
 */
class Inventaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_inv;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity=LigneInventaire::class, mappedBy="inventaire", cascade={"persist"}, orphanRemoval=true)
     */
    private $ligneInventaires;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="inventaires")
     */
    private $user;

    public function __construct()
    {
        $this->ligneInventaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumInv(): ?string
    {
        return $this->num_inv;
    }

    public function setNumInv(string $num_inv): self
    {
        $this->num_inv = $num_inv;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection|LigneInventaire[]
     */
    public function getLigneInventaires(): Collection
    {
        return $this->ligneInventaires;
    }

    public function addLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if (!$this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires[] = $ligneInventaire;
            $ligneInventaire->setInventaire($this);
        }

        return $this;
    }

    public function removeLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if ($this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires->removeElement($ligneInventaire);
            // set the owning side to null (unless already changed)
            if ($ligneInventaire->getInventaire() === $this) {
                $ligneInventaire->setInventaire(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Stock.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StockRepository")
 */
class Stock
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte_reste;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="stocks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\LigneEntree", inversedBy="stocks",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $ligne_entree;

    /**
     * @ORM\ManyToMany(targetEntity=LigneSortie::class, mappedBy="stocks")
     */
    private $ligneSorties;

    /**
     * @ORM\OneToMany(targetEntity=LigneInventaire::class, mappedBy="stock")
     */
    private $ligneInventaires;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="stocks")
     */
    private $user;
   

    public function __construct()
    {
        $this->ligneSorties = new ArrayCollection();
        $this->ligneInventaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(int $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getQteReste(): ?int
    {
        return $this->qte_reste;
    }

    public function setQteReste(int $qte_reste): self
    {
        $this->qte_reste = $qte_reste;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getLigneEntree(): ?LigneEntree
    {
        return $this->ligne_entree;
    }

    public function setLigneEntree(?LigneEntree $ligne_entree): self
    {
        $this->ligne_entree = $ligne_entree;

        return $this;
    }

    /**
     * @return Collection|LigneSortie[]
     */
    public function getLigneSorties(): Collection
    {
        return $this->ligneSorties;
    }

    public function addLigneSorty(LigneSortie $ligneSorty): self
    {
        if (!$this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties[] = $ligneSorty;
            $ligneSorty->addStock($this);
        }

        return $this;
    }

    public function removeLigneSorty(LigneSortie $ligneSorty): self
    {
        if ($this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties->removeElement($ligneSorty);
            $ligneSorty->removeStock($this);
        }

        return $this;
    }

    /**
     * @return Collection|LigneInventaire[]
     */
    public function getLigneInventaires(): Collection
    {
        return $this->ligneInventaires;
    }

    public function addLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if (!$this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires[] = $ligneInventaire;
            $ligneInventaire->setStock($this);
        }
        return $this;
    }

    public function removeLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if ($this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires->removeElement($ligneInventaire);
            // set the owning side to null (unless already changed)
            if ($ligneInventaire->getStock() === $this) {
                $ligneInventaire->setStock(null);
            }
        }
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public  function __toString()
    {
        // TODO: Implement __toString() method.
        $q = $this->getQteReste();
        return (string)$q;

        // return " ";

    }
}

src/Controller/InventaireController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\ArticleSearch;
use App\Entity\Categorie;
use App\Entity\Inventaire;
use App\Entity\LigneInventaire;
use App\Entity\Societe;
use App\Entity\Stock;
use App\Entity\StockSearch;
use App\Entity\Type;
use App\Form\ArticleSearchType;
use App\Form\InventaireType;
use App\Form\LigneInventaireType;
use App\Form\StockSearchType;
use App\Repository\InventaireRepository;
use App\Repository\LigneInventaireRepository;
use App\Repository\StockRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Routing\Annotation\Route;
// Include JSON Response
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/inventaire")
 * @IsGranted("ROLE_ENTREPRISE", message="ليس لديك الحق في الدخول الى هذه الصفحةّ")
 */
class InventaireController extends AbstractController
{
    /**
     * @Route("/list", name="ligne_inventaire_list", methods={"GET"})
     */
    public function list(InventaireRepository $inventaireRepository, LigneInventaireRepository $ligneInventaireRepository): Response
    {
        $user= $this->getUser();


       // $inv= $inventaireRepository->findOneBy(['date' => new \Datetime(date('y-m-d'))]);
       // $inv= $inventaireRepository->findBy(['date' => new \Datetime('now')]);
        $inv= $inventaireRepository->getByCurrentUser($user->getId());

       // dump($inv);die();
        $ligneInventaires= $ligneInventaireRepository->findBy(['inventaire'=> $inv]);


    if (!$inv)

        //throw $this->createNotFoundException('لم تقم يالجرد اليومي بهذا اليوم');
     $this->addFlash('danger', 'لم تقم يالجرد اليومي بهذا اليوم  ');
        //return $this->redirectToRoute("inventaire_new");
        //dump($ligneInventaires);die();

        return $this->render('inventaire/list.html.twig', [
            'ligne_inventaires' =>  $ligneInventaires
            // 'ligne_inventaires' =>  $ligneInventaireRepository->findAll()
        ]);
    }

    /**
     * @Route("/annuel", name="inventaire_index")
     *
     */
    public function index( Request $request, PaginatorInterface $paginator)
    {
        $em = $this->getDoctrine()->getManager();
        $inventaires = $paginator->paginate(
            $result = $em->getRepository(Inventaire::class)
                ->findInventaireByUser($this->getUser()->getId()),
            $request->query->getInt('page', 1), 10
        );
       // dump($inventaires);die();
        //$inventaires = $em->getRepository(Inventaire::class)->findAll();
        return $this->render('inventaire/index.html.twig', array(
            'inventaires' => $inventaires,
            // 'sousMenu' => array(['nom' => 'المواد', 'url' => 'article_new'])

        ));
    }




    /**
     * @Route("/", name="inventaire_new")
     * @Route("/edit/{id}", name="inventaire_edit")
     *
     */
    public function new($id = null, Request $request, PaginatorInterface $paginator)
    {
        $em = $this->getDoctrine()->getManager();
        if (is_null($id))
        {$inventaire = new Inventaire();

        $form = $this->createForm(InventaireType::class, $inventaire);
        $form->handleRequest($request);
        if ($request->isMethod('POST') && $form->isValid()) {

            $user = $this->getUser();
            $inventaire->setUser($user);

            $em->persist($inventaire);
            $em->flush();

            $this->addFlash('success', "تمت العملية بنجاح");
            return $this->redirectToRoute("inventaire_show", ['id'=> $inventaire->getId()]);
        }}
        else{
            $inventaire = $em->find(Inventaire::class, $id);

        $form = $this->createForm(InventaireType::class, $inventaire);
        $form->handleRequest($request);
        if ($request->isMethod('POST') && $form->isValid()) {

            $user = $this->getUser();
            $inventaire->setUser($user);

            $em->persist($inventaire);
            $em->flush();

            $this->addFlash('success', "تمت العملية بنجاح");
            return $this->redirectToRoute("inventaire_new");
        }}
        $inventaires = $paginator->paginate(
            $result = $em->getRepository(Inventaire::class)
                ->findInventaireByUser($this->getUser()->getId()),
            $request->query->getInt('page', 1), 10
        );
        //$inventaires = $em->getRepository(Inventaire::class)->findAll();
        return $this->render('inventaire/new.html.twig', array(
            'form' => $form->createView(),
            'inventaires' => $inventaires,
            // 'sousMenu' => array(['nom' => 'المواد', 'url' => 'article_new'])

        ));
    }

    /**
     * @Route("/new", name="inventaire_ajout", methods={"GET","POST"})
     */
    public function ajout(Request $request): Response
    {
        $inventaire = new Inventaire();
        $form = $this->createForm(InventaireType::class, $inventaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($inventaire);
            $entityManager->flush();

            return $this->redirectToRoute('inventaire_index');
        }

        return $this->render('inventaire/new.html.twig', [
            'inventaire' => $inventaire,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}/show", name="inventaire_show", methods={"GET", "POST"})
     */
    public function show( Inventaire $inventaire, Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();
        $ligneInventaire = new LigneInventaire();

        $form = $this->createForm(LigneInventaireType::class, $ligneInventaire);
        $form->handleRequest($request);

        if ($request->isMethod('POST') && $form->isValid())
        {
            $ligneInventaire->setInventaire($inventaire);


            $em->persist($ligneInventaire);
            $em->persist($inventaire);
            $em->flush();
            $this->addFlash('success', "تمت العملية بنجاح");
            //  dump($ligneEntree);die();
            return $this->redirectToRoute("inventaire_show", ['id' => $inventaire->getId()]);
            // return $this->redirectToRoute("entree_show", ['id'=> $ligneEntree->getEntree()->getId()]);
        }

        $ligneInventaires = $em->getRepository(LigneInventaire::class)->findAll();
        return $this->render('inventaire/show.html.twig', [
            'inventaire' => $inventaire,
            'ligne_inventaires' => $ligneInventaires,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/{id}/edit", name="inventaire_editt", methods={"GET","POST"})
     */
    public function editt(Request $request, Inventaire $inventaire): Response
    {
        $form = $this->createForm(InventaireType::class, $inventaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('inventaire_new');
        }

        return $this->render('inventaire/edit.html.twig', [
            'inventaire' => $inventaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="inventaire_delete")
     */

    /*public function delete(Request $request, Inventaire $inventaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$inventaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($inventaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('inventaire_new');
    }*/
    public function delete(Inventaire $id)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($id);
        $em->flush();
        $this->addFlash('success', "تم الحذف بنجاح");
        return $this->redirectToRoute('inventaire_new');
    }



    /**
     * @Route("/search/inventaire", name="inventaire_search")
     *
     */
    public function search( Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();
        $search= new ArticleSearch();
        // $search->page = $request->get('page', 1);
        $form_search = $this->createForm(ArticleSearchType::class, $search);
        $form_search->handleRequest($request);
        if ($form_search->isSubmitted() && $form_search->isValid()) {
            $categorie = $form_search["categorie"]->getData();
            $type = $form_search["type"]->getData();

            return $this->redirectToRoute('pdfinv',[
                'categorie'=> $categorie->getId(),
                'type'=> $type->getId()
            ]);
        }
        $articles = $em->getRepository(Article::class)->findSearch($search);
        // dump($articles);die();

        return $this->render('search/search1.html.twig', array(
            //  'form' => $form->createView(),
            'articles' => $articles,
            'form_search' => $form_search->createView(),
        ));
    }
// ------- طباعة بطاقة جرد   ----------             //
    /**
     * @Route("/pdfinv/categorie/{categorie}/type/{type}", name="pdfinv")
     * @return response
     */
    public function pdfinvAction($categorie, $type)
    {
        $articles = $this->getDoctrine()
            ->getRepository(Article::class)->getArticles($categorie, $type);
        // dump($articles);die();
        $ids = array();  //creation de tableau vide
        foreach($articles as $article) {
            $id= $article->getId();
            array_push($ids, $id);//remplissage du tableau  avec les ids
        }

templates/inventaire/_delete_form.html.twig
<form method="post" action="{{ path('inventaire_delete', {'id': inventaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inventaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/inventaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<div class="text-right">
    <button class="btn btn-primary" id="appbundle_stock_article"><i class="glyphicon glyphicon-save" style="margin-left: 1rem"></i>{{ button_label|default('Save')|trans }}</button>
</div>
{{ form_end(form) }}

templates/inventaire/index.html.twig
{% extends 'base.html.twig' %}
{% import "form.html.twig" as formulaire %}
{# {% block title %} {{ app.user.email|upper }} {% endblock %} #}

{% block body_class %} class="nav-md" {% endblock %}
{% block body %}

    {#<div class="layout-boxed navbar-top">#}
    {% include('layout/navbar.html.twig') %}
    <!-- Page container -->
    <div class="page-container">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Page header -->
                <div class="col-md-12">
                    <div class="page-header page-header-default">
                        <div class="page-header-content">
                            <div class="page-title">

                            </div>
                        </div>
                        <div class="breadcrumb-line">
                            <ul class="breadcrumb">
                                <li><a href="#"><i class="icon-home2 position-left"></i> الجرد</a></li>
                                <li class="active">الجرد السنوي</li>
                            </ul>

                        </div>
                    </div>
                </div>
                <!-- /page header -->
                <!-- Content area -->
                <div class="col-md-12">
                    <div class="panel">

                        <div class="col-md-12">
                            <div class="panel">
                                <div class="title">
                                    <h1> &nbsp;{{ "Inventaire index"|trans }}&nbsp;&nbsp; </h1>

                                    <hr>
                                </div>
                                <div class="content">
                                    <div class="row">

                                        <table class="table table-bordered">
                                            <thead>

                                            <tr class="bg-orange-800">
                                                <th>{{ "Date"|trans }}</th>
                                                <th>{{ "Num inv"|trans }}</th>

                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for inventaire in inventaires|sort|reverse %}
                                                <tr>
                                                    <td>{{ inventaire.date ? inventaire.date|date('Y-m-d') : '' }}</td>
                                                    <td>{{ inventaire.numInv }}</td>

                                                </tr>
                                            {% else %}
                                                <tr class="text-center">
                                                    <td colspan="3">{{ "no records found"|trans }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                        <br>
                                        <br>
                                        <div class="text-right" >
                                            {{ knp_pagination_render(inventaires) }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /content area -->
            </div>
            <!-- /main content -->

        </div>
        <!-- /page content -->
        {% include('layout/footer.html.twig') %}
    </div>
    <!-- /page container -->
    {#</div>
    </div>#}
{% endblock %}

templates/inventaire/inventaire.html.twig
{% extends 'base.html.twig' %}
{% import "form.html.twig" as formulaire %}
{# {% block title %} {{ app.user.email|upper }} {% endblock %} #}

{% block body_class %} class="nav-md" {% endblock %}
{% block body %}

    {#<div class="layout-boxed navbar-top">#}
    {% include('layout/navbar.html.twig') %}
    <!-- Page container -->
    <div class="page-container">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Page header -->
                <div class="col-md-12">
                    <div class="page-header page-header-default">
                        <div class="page-header-content">
                            <div class="page-title">

                            </div>
                        </div>
                        <div class="breadcrumb-line">
                            <ul class="breadcrumb">
                                <li><a href="#"><i class="icon-home2 position-left"></i> الملف</a></li>
                                <li class="active">الجرد</li>
                            </ul>

                        </div>
                    </div>
                </div>
                <!-- /page header -->
                <!-- Content area -->
                <div class="col-md-12">
                    <div class="panel">
                        <div class="col-md-12">

                            <!-- Basic layout-->
                            <div class="panel panel-flat">
                                <div class="panel-heading">
                                    <h1 class="panel-title">{{ form.vars.value.id == null ? "New inventaire"|trans :"Edit information"|trans }}</h1>
                                    <div class="heading-elements">
                                        <ul class="icons-list">
                                            <li><a data-action="collapse"></a></li>
                                        </ul>
                                    </div>
                                    {% include('layout/flash-messages.html.twig') %}
                                </div>
                                <hr>

                                <div class="panel-body">
                                    {{ form_start(form, {'attr': {'class': 'form-horizontal form-label-left'}}) }}
                                    <div class="form-group">
                                        <label class="col-lg-3 control-label" required="required">{{ "Num inv"|trans }} </label>

                                        <div class="col-lg-6">
                                            {{ form_widget(form.numInv,{'attr': {'class':'form-control col-lg-6'} }) }}
                                        </div>
                                    </div>
#}
                                    <div class="form-group">
                                        <label class="col-lg-3 control-label">{{ "Date"|trans }}</label>
                                        <div class="col-lg-6">
                                            {{ form_widget(form.date,{'attr': {'class':'form-control col-lg-6'} }) }}
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="form-group">
                                        {{ include('inventaire/_form.html.twig') }}
                                    </div>
                                    {{ form_end(form) }}
                                    {# {{ form_widget(form._token) }}
                                     {{ form_end(form, {'render_rest': false}) }}#}
                                </div>
                            </div>
                            <!-- /basic layout -->

                        </div>

                        <div class="col-md-12">
                            <div class="panel">
                                <div class="title">
                                    <h1> &nbsp;{{ "Inventaire index"|trans }}&nbsp;&nbsp; </h1>

                                    <hr>
                                </div>
                                <div class="content">
                                    <div class="row">

                                        <table class="table table-bordered">
                                            <thead>

                                            <tr class="bg-orange-800">
                                                <th>{{ "Date"|trans }}</th>
                                                <th>{{ "Num inv"|trans }}</th>
                                                <th class="text-right">
                                                    <a href="{{ path('inventaire_new') }}" class="btn btn-success btn-rounded">
                                                        <i class="glyphicon  glyphicon-plus" style="margin-left: 1rem"></i>{{ "Create new inventaire"|trans }} </a>
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for inventaire in inventaires|sort|reverse %}
                                                <tr>
                                                    <td>{{ inventaire.date ? inventaire.date|date('Y-m-d') : '' }}</td>
                                                    <td>{{ inventaire.numInv }}</td>
                                                    <td>
                                                        {# <a href="{{ path('article_show', {'id': article.id}) }}" class="btn btn-default btn-rounded"><i class="glyphicon  glyphicon-search"></i>
                                                             {{ "show"|trans }}
                                                         </a>#}
                                                        <a href="{{ path('inventaire_edit', {'id': inventaire.id}) }}" class="btn btn-primary btn-rounded"><i class="glyphicon  glyphicon-edit" style="margin-left: 1rem"></i>
                                                            {{ "edit"|trans }}
                                                        </a>
                                                        <a href="{{ path('inventaire_delete', {'id': inventaire.id}) }}" class="btn btn-danger btn-rounded"><i class="glyphicon  glyphicon-trash" style="margin-left: 1rem"></i>
                                                            {{ "Delete"|trans }}
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% else %}
                                                <tr class="text-center">
                                                    <td colspan="3">{{ "no records found"|trans }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                        <br>
                                        <br>
                                                <div class="text-right" >
                                                    {{ knp_pagination_render(inventaires) }}
                                                </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /content area -->
            </div>
            <!-- /main content -->

        </div>
        <!-- /page content -->
        {% include('layout/footer.html.twig') %}
    </div>
    <!-- /page container -->
    {#</div>
    </div>#}
{% endblock %}