src/Entity/Annee.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnneeRepository")
 */
class Annee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libele_an;

    /**
     * @ORM\Column(type="boolean")
     */
    private $courante;

    /**
     * @ORM\OneToMany(targetEntity=Sortie::class, mappedBy="annee")
     */
    private $sorties;

    public function __construct()
    {
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibeleAn(): ?string
    {
        return $this->libele_an;
    }

    public function setLibeleAn(string $libele_an): self
    {
        $this->libele_an = $libele_an;

        return $this;
    }

    public function getCourante(): ?bool
    {
        return $this->courante;
    }

    public function setCourante(bool $courante): self
    {
        $this->courante = $courante;

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sortie $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->setAnnee($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): self
    {
        if ($this->sorties->contains($sorty)) {
            $this->sorties->removeElement($sorty);
            // set the owning side to null (unless already changed)
            if ($sorty->getAnnee() === $this) {
                $sorty->setAnnee(null);
            }
        }

        return $this;
    }
    public  function __toString()
    {
        return $this->libele_an;
        // TODO: Implement __toString() method.
    }
}

src/Form/AnneeType.php
<?php

namespace App\Form;

use App\Entity\Annee;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnneeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libele_an')
            ->add('courante', CheckboxType::class, [
                 'label'    => 'Annee courante',
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Annee::class,
        ]);
    }
}

src/Controller/AnneeController.php
<?php

namespace App\Controller;

use App\Entity\Annee;
use App\Form\AnneeType;
use App\Repository\AnneeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


/**
 * @Route("/annee")
 * @IsGranted("ROLE_ENTREPRISE", message="ليس لديك الحق في الدخول الى هذه الصفحةّ")
 */
class AnneeController extends AbstractController
{
    /**
     * @Route("/", name="annee_new")
     * @Route("/edit/{id}", name="annee_edit")
     */
    public function annee($id = null, Request $request, PaginatorInterface $paginator)
    {
        $em = $this->getDoctrine()->getManager();
        if (is_null($id))
            $annee = new Annee();
        else
            $annee = $em->find(Annee::class, $id);

        $form = $this->createForm(AnneeType::class, $annee);
        $form->handleRequest($request);
        if ($request->isMethod('POST') && $form->isValid()) {
            $em->persist($annee);
            $em->flush();

            $this->addFlash('success', "تمت العملية بنجاح");
            return $this->redirectToRoute("annee_new");
        }

        $annees = $paginator->paginate(
            $result = $em->getRepository(Annee::class)->findAll(), // Requête contenant les données à paginer (ici nos annees)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            10 // Nombre de résultats par page
        );
        // $annees = $em->getRepository(Annee::class)->findAll();
        return $this->render('annee/annee.html.twig', array(
            'form' => $form->createView(),
            'annees' => $annees,
            // 'sousMenu' => array(['nom' => 'المواد', 'url' => 'article_new'])

        ));
    }
    
    /**
     * @Route("/{id}", name="annee_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Annee $annee, $id): Response
    {
        if ($this->isCsrfTokenValid('delete'.$annee->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($annee);
            $entityManager->flush();
        }

        return $this->redirectToRoute('annee_new');
    }
        
        }

templates/annee/_delete_form.html.twig
<form method="post" action="{{ path('annee_delete', {'id': annee.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ annee.id) }}">
    <button class="btn">Delete</button>
</form>

templates/annee/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<div class="text-right">
    <button class="btn btn-primary"><i class="glyphicon glyphicon-save" style="margin-left: 1rem"></i>{{ button_label|default('Save')|trans }}</button>
</div>
{{ form_end(form) }}

templates/annee/annee.html.twig
{% extends 'base.html.twig' %}

{# {% block title %} {{ app.user.email|upper }} {% endblock %} #}
{% block body_class %} class="nav-md" {% endblock %}
{% block body %}
    {#<div class="layout-boxed navbar-top">#}
    {% include('layout/navbar.html.twig') %}
    <!-- Page container -->
    <div class="page-container">

        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Page header -->
                <div class="page-header page-header-default">
                    <div class="page-header-content">
                        <div class="page-title">

                        </div>
                    </div>

                    <div class="breadcrumb-line">
                        <ul class="breadcrumb">
                            <li><a href="#"><i class="icon-home2 position-left"></i> الملف</a></li>
                            <li class="active">السنة المالية</li>
                        </ul>

                    </div>
                </div>
                <!-- /page header -->
                <!-- Content area -->
                <div class="col-md-12">
                    <div class="panel">
                        <div class="col-md-12">

                            <!-- Basic layout-->
                            <div class="panel panel-flat">
                                <div class="panel-heading">
                                    <h1 class="panel-title">{{ "Info Annee"|trans }}</h1>
                                    <div class="heading-elements">
                                        <ul class="icons-list">
                                            <li><a data-action="collapse"></a></li>
                                        </ul>
                                    </div>
                                    {% include('layout/flash-messages.html.twig') %}
                                </div>
                                <hr>

                                <div class="panel-body">
                                    {{ form_start(form, {'attr': {'class': 'form-horizontal form-label-left'}}) }}
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label">{{ "Libele an"|trans }}</label>
                                        <div class="col-lg-2">
                                            {{ form_widget(form.libele_an,{'attr': {'class':'form-control col-lg-2'} }) }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        {# <label class="col-lg-3 control-label">{{ "Annee courante"|trans }}</label> #}
                                        <div class="col-lg-3">
                                            {# {{ form_widget(form.courante,{'attr': {'class':'form-control col-lg-1'} }) }} #}
                                        {{ form_widget(form.courante) }}

                                        </div>
                                    </div>


                                    <hr>
                                    <div class="form-group">
                                        {{ include('annee/_form.html.twig') }}
                                    </div>
                                    {{ form_end(form) }}

                                </div>
                            </div>
                            <!-- /basic layout -->

                        </div>

                        <div class="col-md-12">
                            <div class="panel">
                                <div class="title">
                                    {#<h1> &nbsp;{{ "Annee index"|trans }}&nbsp;&nbsp; </h1>#}
                                    <hr>
                                </div>
                                <div class="content">
                                    <div class="row">

                                        <table class="table table-bordered">
                                            <thead>
                                            <tr class="bg-orange-800">
                                                <th>{{ "Libele an"|trans }}</th>
                                                <th>{{ "Annee courante"|trans }}</th>
                                                <th class="text-right">
                                                    <a href="{{ path('annee_new') }}" class="btn btn-success btn-rounded">
                                                        <i class="glyphicon  glyphicon-plus" style="margin-left: 1rem"></i>{{ "Create new Annee"|trans }} </a>
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for annee in annees %}
                                                <tr>
                                                    <td>{{ annee.libeleAn }}</td>
                                                    <td>{{ annee.courante ? 'نعم' : 'لا' }}</td>
                                                    <td>
                                                        {# <a href="{{ path('annee_show', {'id': annee.id}) }}" class="btn btn-default btn-rounded"><i class="glyphicon  glyphicon-search"></i>
                                                             {{ "show"|trans }}
                                                         </a>#}
                                                        <a href="{{ path('annee_edit', {'id': annee.id}) }}" class="btn btn-primary btn-rounded"><i class="glyphicon  glyphicon-edit" style="margin-left: 1rem"></i>
                                                            {{ "edit"|trans }}
                                                        </a>
                                                        <a href="{{ path('annee_delete', {'id': annee.id}) }}" class="btn btn-danger btn-rounded"><i class="glyphicon  glyphicon-trash" style="margin-left: 1rem"></i>
                                                            {{ "Delete"|trans }}
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% else %}
                                                <tr class="text-center">
                                                    <td colspan="3">{{ "no records found"|trans }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                        <br>
                                            <div class="text-right" >
                                                {{ knp_pagination_render(annees) }}
                                            </div>  
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /content area -->
            </div>
            <!-- /main content -->

        </div>
        <!-- /page content -->
        {% include('layout/footer.html.twig') %}
    </div>
    <!-- /page container -->
    {#</div>#}

{% endblock %}

templates/annee/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annee{% endblock %}

{% block body %}
    <h1>Annee</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ annee.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ annee.libelle }}</td>
            </tr>
            <tr>
                <th>Designation</th>
                <td>{{ annee.designation ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('annee_index') }}">back to list</a>

    <a href="{{ path('annee_edit', {'id': annee.id}) }}">edit</a>

    {{ include('annee/_delete_form.html.twig') }}
{% endblock %}