src/Entity/Entree.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EntreeRepository")
 */
class Entree
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $dateEntree;

    /**
     * @ORM\Column(type="date")
     */
    private $date_bc;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_entree;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_bc;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Fournisseur", inversedBy="entrees")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fournisseur;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneEntree", mappedBy="entree")
     */
    private $ligneEntrees;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="entrees")
     */
    private $user;

    public function __construct()
    {
        $this->ligneEntrees = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEntree(): ?\DateTimeInterface
    {
        return $this->dateEntree;
    }

    public function setDateEntree(\DateTimeInterface $dateEntree): self
    {
        $this->dateEntree = $dateEntree;

        return $this;
    }

    public function getDateBc(): ?\DateTimeInterface
    {
        return $this->date_bc;
    }

    public function setDateBc(\DateTimeInterface $date_bc): self
    {
        $this->date_bc = $date_bc;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getNumEntree(): ?string
    {
        return $this->num_entree;
    }

    public function setNumEntree(string $num_entree): self
    {
        $this->num_entree = $num_entree;

        return $this;
    }

    public function getNumBc(): ?string
    {
        return $this->num_bc;
    }

    public function setNumBc(string $num_bc): self
    {
        $this->num_bc = $num_bc;

        return $this;
    }

    public function getFournisseur(): ?Fournisseur
    {
        return $this->fournisseur;
    }

    public function setFournisseur(?Fournisseur $fournisseur): self
    {
        $this->fournisseur = $fournisseur;

        return $this;
    }

    /**
     * @return Collection|LigneEntree[]
     */
    public function getLigneEntrees(): Collection
    {
        return $this->ligneEntrees;
    }

    public function addLigneEntree(LigneEntree $ligneEntree): self
    {
        if (!$this->ligneEntrees->contains($ligneEntree)) {
            $this->ligneEntrees[] = $ligneEntree;
            $ligneEntree->setEntree($this);
        }

        return $this;
    }

    public function removeLigneEntree(LigneEntree $ligneEntree): self
    {
        if ($this->ligneEntrees->contains($ligneEntree)) {
            $this->ligneEntrees->removeElement($ligneEntree);
            // set the owning side to null (unless already changed)
            if ($ligneEntree->getEntree() === $this) {
                $ligneEntree->setEntree(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/Societe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SocieteRepository")
 */
class Societe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom_soc;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ministere;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $siege;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $magasinier;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $directeur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fax;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="societes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSoc(): ?string
    {
        return $this->Nom_soc;
    }

    public function setNomSoc(string $Nom_soc): self
    {
        $this->Nom_soc = $Nom_soc;

        return $this;
    }

    public function getMinistere(): ?string
    {
        return $this->ministere;
    }

    public function setMinistere(string $ministere): self
    {
        $this->ministere = $ministere;

        return $this;
    }

    public function getSiege(): ?string
    {
        return $this->siege;
    }

    public function setSiege(string $siege): self
    {
        $this->siege = $siege;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getMagasinier(): ?string
    {
        return $this->magasinier;
    }

    public function setMagasinier(string $magasinier): self
    {
        $this->magasinier = $magasinier;

        return $this;
    }

    public function getDirecteur(): ?string
    {
        return $this->directeur;
    }

    public function setDirecteur(string $directeur): self
    {
        $this->directeur = $directeur;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SortieRepository::class)
 */
class Sortie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bon_sortie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num;

    /**
     * @ORM\OneToMany(targetEntity=LigneSortie::class, mappedBy="sortie")
     */
    private $ligneSorties;

    /**
     * @ORM\ManyToOne(targetEntity=Annee::class, inversedBy="sorties")
     */
    private $annee;

    /**
     * @ORM\ManyToOne(targetEntity=Benificiaire::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $benificiaire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="sorties")
     */
    private $user;

    public function __construct()
    {
        $this->ligneSorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getBonSortie(): ?string
    {
        return $this->bon_sortie;
    }

    public function setBonSortie(string $bon_sortie): self
    {
        $this->bon_sortie = $bon_sortie;

        return $this;
    }

    public function getNum(): ?string
    {
        return $this->num;
    }

    public function setNum(string $num): self
    {
        $this->num = $num;

        return $this;
    }

    /**
     * @return Collection|LigneSortie[]
     */
    public function getLigneSorties(): Collection
    {
        return $this->ligneSorties;
    }

    public function addLigneSorty(LigneSortie $ligneSorty): self
    {
        if (!$this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties[] = $ligneSorty;
            $ligneSorty->setSortie($this);
        }

        return $this;
    }

    public function removeLigneSorty(LigneSortie $ligneSorty): self
    {
        if ($this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties->removeElement($ligneSorty);
            // set the owning side to null (unless already changed)
            if ($ligneSorty->getSortie() === $this) {
                $ligneSorty->setSortie(null);
            }
        }

        return $this;
    }

    public function getAnnee(): ?Annee
    {
        return $this->annee;
    }

    public function setAnnee(?Annee $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    public function getBenificiaire(): ?Benificiaire
    {
        return $this->benificiaire;
    }

    public function setBenificiaire(?Benificiaire $benificiaire): self
    {
        $this->benificiaire = $benificiaire;

        return $this;
    }
    public  function __toString()
    {
        return $this->bon_sortie;
        // TODO: Implement __toString() method.
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Stock.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StockRepository")
 */
class Stock
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte_reste;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="stocks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\LigneEntree", inversedBy="stocks",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $ligne_entree;

    /**
     * @ORM\ManyToMany(targetEntity=LigneSortie::class, mappedBy="stocks")
     */
    private $ligneSorties;

    /**
     * @ORM\OneToMany(targetEntity=LigneInventaire::class, mappedBy="stock")
     */
    private $ligneInventaires;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="stocks")
     */
    private $user;
   

    public function __construct()
    {
        $this->ligneSorties = new ArrayCollection();
        $this->ligneInventaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(int $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getQteReste(): ?int
    {
        return $this->qte_reste;
    }

    public function setQteReste(int $qte_reste): self
    {
        $this->qte_reste = $qte_reste;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getLigneEntree(): ?LigneEntree
    {
        return $this->ligne_entree;
    }

    public function setLigneEntree(?LigneEntree $ligne_entree): self
    {
        $this->ligne_entree = $ligne_entree;

        return $this;
    }

    /**
     * @return Collection|LigneSortie[]
     */
    public function getLigneSorties(): Collection
    {
        return $this->ligneSorties;
    }

    public function addLigneSorty(LigneSortie $ligneSorty): self
    {
        if (!$this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties[] = $ligneSorty;
            $ligneSorty->addStock($this);
        }

        return $this;
    }

    public function removeLigneSorty(LigneSortie $ligneSorty): self
    {
        if ($this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties->removeElement($ligneSorty);
            $ligneSorty->removeStock($this);
        }

        return $this;
    }

    /**
     * @return Collection|LigneInventaire[]
     */
    public function getLigneInventaires(): Collection
    {
        return $this->ligneInventaires;
    }

    public function addLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if (!$this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires[] = $ligneInventaire;
            $ligneInventaire->setStock($this);
        }
        return $this;
    }

    public function removeLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if ($this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires->removeElement($ligneInventaire);
            // set the owning side to null (unless already changed)
            if ($ligneInventaire->getStock() === $this) {
                $ligneInventaire->setStock(null);
            }
        }
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public  function __toString()
    {
        // TODO: Implement __toString() method.
        $q = $this->getQteReste();
        return (string)$q;

        // return " ";

    }
}

templates/pdf/carte1.html.twig
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="UTF-8">
    <title>طباعة بطاقة مخزون</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        table {
            font-family: xbriyaz, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }
        td, th {
            border: 1px solid #000;
            text-align: left;
            padding: 8px;
        }
        .flotte {
            float:right;
        }
    </style>
</head>
<body style="font-family:xbriyaz,sans-serif">
{# {% include('pdf/header.html.twig') %} #}

{#<img src="assets/images/logo.png" alt="logo.png"/>#}
{# <h3 style="text-align: left; ">
    التاريخ:
    {{ "now"|date('d-m-Y') }}</h3> #}
{#{% for stock in stocks %}
    {% if loop.first %}
        <h3 style="text-align: left"> التاريخ: {{ stock.date | date('d-m-Y')  }}</h3>
    {% endif %}
{% endfor %}#}
<table >
        <tr>
        <td  style="border:0;text-align: right;">{% include('pdf/header.html.twig') %}</td>
        <td  style="border:0;text-align: right;">
                <table>
                <tr><td  style="text-align: right;">عدد التدوين :</td></tr>
                <tr> <td style="text-align: right;" >رقم المرجع :</td></tr>
                <tr>  <td style="text-align: right;"> المخزون الادنى: {{ article.qteMin }}</td></tr>
                </table>
        </td></tr>
 </table>   
<h1 style="text-align: center; "> بطاقة مخزون</h1>
<h3 style="text-align: center; ">رقم الرف ............................</h3>
<br>
<h3 style="text-align: right; "> نوع المادة:{{ article }}</h3>

{#<p class="flotte">
    <img src="{{ asset('assets/images/print1.png')}}" alt="">
</p>#}

<table class="table table-bordered">
    <thead>
    <tr >
        <th colspan="5" style="text-align: center">{{ "الدخول"|trans }}</th>
        <th colspan="4" style="text-align: center">{{ "الخروج"|trans }}</th>
        <td rowspan="2" style="text-align: center">{{ "Reste"|trans }}</td>
        <td rowspan="2" style="text-align: center">{{ "Remarques"|trans }}</td>
    </tr>

{#    <tbody>#}
{#    {% for stock in stocks|sort|reverse %}#}
        <tr>
            <td style="text-align: center">{{ "عدد التسجيل"|trans }}</td>
            <td style="text-align: center">{{ "Date"|trans }}</td>
            <td style="text-align: center">{{ "Qte"|trans }}</td>
            <td style="text-align: center">{{ "عدد وصل التسليم"|trans }}</td>
            <td style="text-align: center">{{ "رقم الطلبية
و تاريخها أو المصدر"|trans }}</td>
            <td style="text-align: center">{{ "Date"|trans }}</td>
            <td style="text-align: center">{{ "عدد وصل الخروج"|trans }}</td>
            <td style="text-align: center">{{ "Qte"|trans }}</td>
            <td style="text-align: center">{{ "Benificiaire"|trans }}</td>



        </tr>
    </thead>
    <tbody>
{% for date in dates %}
 {% for ligne_sortie in ligne_sorties|sort|reverse %}
         {% set ds= ligne_sortie.sortie.date|date('Y-m-d') %}
{% for ligne_entree in ligne_entrees|sort|reverse %}
        {% set de = ligne_entree.entree.dateEntree|date('Y-m-d') %}
{#    {% if loop.first %}#}
   

           
            {% if date==de and date!= ds %}
             <tr>
                {% if loop.first %}
                    <td style="text-align: center">{{ ligne_entree.entree.numEntree }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.dateEntree ? ligne_entree.entree.dateEntree|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center">{{ ligne_entree.qteEntr }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.reference }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.numBc }}--{{ ligne_entree.entree.dateBc ? ligne_entree.entree.dateBc|date('Y-m-d') : '' }}</td>
                    
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center">{{ ligne_entree.qteEntr }}</td>
                    <td style="text-align: center">{{ ligne_entree.article.remarque }}</td>
                {% endif %}
             </tr> 
                  {% elseif date!=de and date == ds  %}
             <tr>
                {% if loop.first %}
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    
                 <td style="text-align: center">{{ ligne_sortie.sortie.date ? ligne_sortie.sortie.date|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center">{{ ligne_sortie.sortie.bonSortie }}</td>
                    <td style="text-align: center">{{ ligne_sortie.qte }}</td>
                    <td style="text-align: center">{{ ligne_sortie.sortie.benificiaire }}</td>
                    <td style="text-align: center">{{ ligne_sortie.qte }}</td>
                    <td style="text-align: center">{{ ligne_sortie.article.remarque }}</td>
                    {% endif %}
             </tr> 
                 {% elseif date == de and date == ds  %}
             <tr>
                {# {% if loop.first %} #}
                    <td style="text-align: center">{{ ligne_entree.entree.numEntree }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.dateEntree ? ligne_entree.entree.dateEntree|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center">{{ ligne_entree.qteEntr }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.reference }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.numBc }}-- {{ ligne_entree.entree.dateBc ? ligne_entree.entree.dateBc|date('Y-m-d') : '' }}</td>
                    
                    <td style="text-align: center">{{ ligne_sortie.sortie.date ? ligne_sortie.sortie.date|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center">{{ ligne_sortie.sortie.bonSortie }}</td>
                    <td style="text-align: center">{{ ligne_sortie.qte }}</td>
                    <td style="text-align: center">{{ ligne_sortie.sortie.benificiaire }}</td>
                    <td style="text-align: center">{{ ligne_entree.qteEntr - ligne_sortie.qte }}</td>
                    <td style="text-align: center">{{ ligne_sortie.article.remarque }}</td>
                {# {% endif %} #}
                </tr>
             {% endif %}  
             {# {% endif %} #}
    {% endfor %}
{% endfor %}
{% endfor %}






{# {% for ligne_entree in ligne_entrees %}
{#    {% if loop.first %}#}
   {# {% for ligne_sortie in ligne_sorties %}

    {% set de = ligne_entree.entree.dateEntree|date('Y-m-d') %}
    {% set ds= ligne_sortie.sortie.date|date('Y-m-d') %}

     {#{% for entree in entrees|sort|reverse %}#}
         {#   {% if de is defined and ds is defined and de == ds  %}
                <tr>
                {% if loop.first %}
                    <td style="text-align: center">{{ ligne_entree.entree.numEntree }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.dateEntree ? ligne_entree.entree.dateEntree|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center">{{ ligne_entree.qteEntr }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.reference }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.numBc }}</td>
                    
                    <td style="text-align: center">{{ ligne_sortie.sortie.date ? ligne_sortie.sortie.date|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center">{{ ligne_sortie.sortie.bonSortie }}</td>
                    <td style="text-align: center">{{ ligne_sortie.qte }}</td>
                    <td style="text-align: center">{{ ligne_sortie.sortie.benificiaire }}</td>
                    <td style="text-align: center">{{ ligne_entree.qteEntr - ligne_sortie.qte }}</td>
                    <td style="text-align: center"></td>
                    {% endif %}
                </tr>
            {% elseif de is defined or ds is defined  %}
            {% if de is defined %}
             <tr>
                {% if loop.first %}
                    <td style="text-align: center">{{ ligne_entree.entree.numEntree }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.dateEntree ? ligne_entree.entree.dateEntree|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center">{{ ligne_entree.qteEntr }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.reference }}</td>
                    <td style="text-align: center">{{ ligne_entree.entree.numBc }}</td>
                    
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center">{{ ligne_entree.qteEntr }}</td>
                    <td style="text-align: center"></td>
                {% endif %}
             </tr>
                 {% elseif ds is defined  %}
             <tr>
                {% if loop.first %}
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    <td style="text-align: center"></td>
                    
                 <td style="text-align: center">{{ ligne_sortie.sortie.date ? ligne_sortie.sortie.date|date('Y-m-d') : '' }}</td>
                    <td style="text-align: center">{{ ligne_sortie.sortie.bonSortie }}</td>
                    <td style="text-align: center">{{ ligne_sortie.qte }}</td>
                    <td style="text-align: center">{{ ligne_sortie.sortie.benificiaire }}</td>
                    <td style="text-align: center">{{ ligne_sortie.qte }}</td>
                    <td style="text-align: center"></td>
                    {% endif %}
                </tr>
            {% endif %} 
            {% endif %}
    {% endfor %}
{% endfor %}
 #}

    </tbody>
</table>
</body>
</html>

templates/pdf/header.html.twig
    {% for vb in societe %}

    {% if loop.first %}

&nbsp;&nbsp;<h4 style="text-align: right"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  الجمهورية التونسية</h4>

          <h4 style="text-align: right; font-size:18px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     {{ vb.ministere }}</h4>
        <h4 style="text-align: right">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    {{ vb.siege }}</h4>
        <h4 style="text-align: right">    {{ vb.nomSoc }}</h4>


    {% endif %}
    {% endfor %}

templates/pdf/stock0.html.twig
<!DOCTYPE html>
<html dir="rtl" >
<head>
    <meta charset="UTF-8">
    <title>المخزون الحالي</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        table {
            /*font-family: xbriyaz, sans-serif;*/
            border-collapse: collapse;
            width: 100%;
        }
        td, th {
            border: 1px solid #000;
            text-align: left;
            padding: 8px;
        }

    </style>
</head>
{#<body style="font-family:xbriyaz,sans-serif">#}
<body>
{% include('pdf/header.html.twig') %}
<h3 style="text-align: left; ">
    التاريخ:
    {{ "now"|date('d-m-Y') }}</h3>
{#{% for stock in stocks %}
    {% if loop.first %}
        <h3 style="text-align: left"> التاريخ: {{ stock.date | date('d-m-Y')  }}</h3>
    {% endif %}
{% endfor %}#}
<h1 style="text-align: center; "> المخزون الحالي</h1>
<br>
<h3 style="text-align: right; "> الصنف:{{ categorie}}</h3>
<h3 style="text-align: right; ">النوع: {{ type }}</h3>

<table class="table table-bordered">
    <thead>
    <tr >
        <th style="text-align: center">{{ "Libele ar"|trans }}</th>
        <th style="text-align: center">{{ "Qte"|trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% for stock in stocks|sort|reverse %}
        <tr>
            <td style="text-align: center">{{ stock.article }}</td>
            <td style="text-align: center">{{ stock.qteReste }}</td>

        </tr>
    {% else %}
        <tr style="text-align: center">
            <td colspan="2" style="text-align: center">{{ "no records found"|trans }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>