src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libele;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte_min;

  

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneEntree", mappedBy="article")
     */
    private $ligneEntrees;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Stock", mappedBy="article")
     */
    private $stocks;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte_ini;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $remarque;

    /**
     * @ORM\OneToMany(targetEntity=LigneSortie::class, mappedBy="article")
     */
    private $ligneSorties;

    /**
     * @ORM\OneToMany(targetEntity=LigneInventaire::class, mappedBy="article")
     */
    private $ligneInventaires;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     */
    private $user;

    public function __construct()
    {
        $this->ligneEntrees = new ArrayCollection();
        $this->stocks = new ArrayCollection();
        $this->ligneSorties = new ArrayCollection();
        $this->ligneInventaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibele(): ?string
    {
        return $this->libele;
    }

    public function setLibele(string $libele): self
    {
        $this->libele = $libele;

        return $this;
    }

    public function getQteMin(): ?int
    {
        return $this->qte_min;
    }

    public function setQteMin(int $qte_min): self
    {
        $this->qte_min = $qte_min;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|LigneEntree[]
     */
    public function getLigneEntrees(): Collection
    {
        return $this->ligneEntrees;
    }

    public function addLigneEntree(LigneEntree $ligneEntree): self
    {
        if (!$this->ligneEntrees->contains($ligneEntree)) {
            $this->ligneEntrees[] = $ligneEntree;
            $ligneEntree->setArticle($this);
        }

        return $this;
    }

    public function removeLigneEntree(LigneEntree $ligneEntree): self
    {
        if ($this->ligneEntrees->contains($ligneEntree)) {
            $this->ligneEntrees->removeElement($ligneEntree);
            // set the owning side to null (unless already changed)
            if ($ligneEntree->getArticle() === $this) {
                $ligneEntree->setArticle(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this ->libele;
    }

    /**
     * @return Collection|Stock[]
     */
    public function getStocks(): Collection
    {
        return $this->stocks;
    }

    public function addStock(Stock $stock): self
    {
        if (!$this->stocks->contains($stock)) {
            $this->stocks[] = $stock;
            $stock->setArticle($this);
        }

        return $this;
    }

    public function removeStock(Stock $stock): self
    {
        if ($this->stocks->contains($stock)) {
            $this->stocks->removeElement($stock);
            // set the owning side to null (unless already changed)
            if ($stock->getArticle() === $this) {
                $stock->setArticle(null);
            }
        }

        return $this;
    }

    public function getQteIni(): ?int
    {
        return $this->qte_ini;
    }

    public function setQteIni(int $qte_ini): self
    {
        $this->qte_ini = $qte_ini;

        return $this;
    }

    public function getRemarque(): ?string
    {
        return $this->remarque;
    }

    public function setRemarque(?string $remarque): self
    {
        $this->remarque = $remarque;

        return $this;
    }

    /**
     * @return Collection|LigneSortie[]
     */
    public function getLigneSorties(): Collection
    {
        return $this->ligneSorties;
    }

    public function addLigneSorty(LigneSortie $ligneSorty): self
    {
        if (!$this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties[] = $ligneSorty;
            $ligneSorty->setArticles($this);
        }

        return $this;
    }

    public function removeLigneSorty(LigneSortie $ligneSorty): self
    {
        if ($this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties->removeElement($ligneSorty);
            // set the owning side to null (unless already changed)
            if ($ligneSorty->getArticles() === $this) {
                $ligneSorty->setArticles(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|LigneInventaire[]
     */
    public function getLigneInventaires(): Collection
    {
        return $this->ligneInventaires;
    }

    public function addLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if (!$this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires[] = $ligneInventaire;
            $ligneInventaire->setArticles($this);
        }

        return $this;
    }

    public function removeLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if ($this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires->removeElement($ligneInventaire);
            // set the owning side to null (unless already changed)
            if ($ligneInventaire->getArticles() === $this) {
                $ligneInventaire->setArticles(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Stock.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StockRepository")
 */
class Stock
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte_reste;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="stocks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\LigneEntree", inversedBy="stocks",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $ligne_entree;

    /**
     * @ORM\ManyToMany(targetEntity=LigneSortie::class, mappedBy="stocks")
     */
    private $ligneSorties;

    /**
     * @ORM\OneToMany(targetEntity=LigneInventaire::class, mappedBy="stock")
     */
    private $ligneInventaires;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="stocks")
     */
    private $user;
   

    public function __construct()
    {
        $this->ligneSorties = new ArrayCollection();
        $this->ligneInventaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(int $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getQteReste(): ?int
    {
        return $this->qte_reste;
    }

    public function setQteReste(int $qte_reste): self
    {
        $this->qte_reste = $qte_reste;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getLigneEntree(): ?LigneEntree
    {
        return $this->ligne_entree;
    }

    public function setLigneEntree(?LigneEntree $ligne_entree): self
    {
        $this->ligne_entree = $ligne_entree;

        return $this;
    }

    /**
     * @return Collection|LigneSortie[]
     */
    public function getLigneSorties(): Collection
    {
        return $this->ligneSorties;
    }

    public function addLigneSorty(LigneSortie $ligneSorty): self
    {
        if (!$this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties[] = $ligneSorty;
            $ligneSorty->addStock($this);
        }

        return $this;
    }

    public function removeLigneSorty(LigneSortie $ligneSorty): self
    {
        if ($this->ligneSorties->contains($ligneSorty)) {
            $this->ligneSorties->removeElement($ligneSorty);
            $ligneSorty->removeStock($this);
        }

        return $this;
    }

    /**
     * @return Collection|LigneInventaire[]
     */
    public function getLigneInventaires(): Collection
    {
        return $this->ligneInventaires;
    }

    public function addLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if (!$this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires[] = $ligneInventaire;
            $ligneInventaire->setStock($this);
        }
        return $this;
    }

    public function removeLigneInventaire(LigneInventaire $ligneInventaire): self
    {
        if ($this->ligneInventaires->contains($ligneInventaire)) {
            $this->ligneInventaires->removeElement($ligneInventaire);
            // set the owning side to null (unless already changed)
            if ($ligneInventaire->getStock() === $this) {
                $ligneInventaire->setStock(null);
            }
        }
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public  function __toString()
    {
        // TODO: Implement __toString() method.
        $q = $this->getQteReste();
        return (string)$q;

        // return " ";

    }
}

src/Form/StockType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Stock;
use App\Repository\ArticleRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Security\Core\Security;

class StockType extends AbstractType
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date')
            ->add('qte')
            ->add('qte_reste')
          // ->add('article')
        ;
        $user = $this->security->getUser();
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($user) {
            $form = $event->getForm();
            $form->add('article', EntityType::class, [
                'class' => Article::class,
                'query_builder' => function (ArticleRepository $articleRepository)use ($user) {
                    return $articleRepository->findByCurrentUser($user);
                },
            ]);
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stock::class,
        ]);
    }
}

templates/stock/_delete_form.html.twig
<form method="post" action="{{ path('stock_delete', {'id': stock.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stock.id) }}">
    <button class="btn">Delete</button>
</form>

templates/stock/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/stock/index.html.twig
{% extends 'base.html.twig' %}

{# {% block title %} {{ app.user.email|upper }} {% endblock %} #}
{% block body_class %} class="nav-md" {% endblock %}
{% block body %}

    {#<div class="layout-boxed navbar-top">#}
    {% include('layout/navbar.html.twig') %}
    <!-- Page container -->
    <div class="page-container">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Page header -->
                <div class="col-md-12">
                    <div class="page-header page-header-default">
                        <div class="page-header-content">
                            <div class="page-title">

                            </div>
                        </div>
                        <div class="breadcrumb-line">
                            <ul class="breadcrumb">
                                <li><a href="#"><i class="icon-home2 position-left"></i> المخزون</a></li>
                                <li class="active"> المخزون الحالي</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /page header -->
                <!-- Content area -->
                <div class="col-md-12">
                    <div class="panel">
                        <div class="col-md-12">
                            <div class="panel">
                                <div class="title">
                                    <h1> &nbsp;{{ "Stock index"|trans }}&nbsp;&nbsp; </h1>
                                    <div class="text-right">
                                    <a href="{{ path('stock_pdf')}}"  class="btn btn-primary btn-rounded text-right"><i class="glyphicon  glyphicon-print" style="margin-left: 1rem"></i>
                                        {{ "print"|trans }} </a>
                                    </div>
                                    <hr>
                                </div>
                                <div class="content">
                                    <div class="row">
                                        <table class="table table-bordered">
                                            <thead>
                                            <tr class="bg-orange-800">
                                                {#<th>{{ "Date"|trans }}</th>#}
                                                <th>{{ "Libele ar"|trans }}</th>
                                                <th>{{ "Qte old"|trans }}</th>
                                                <th>{{ "Qte en  stock"|trans }}</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for stock in stocks|sort|reverse %}
                                                <tr>
                                                    {#<td>{{ stock.date ? stock.date|date('Y-m-d') : '' }}</td>#}
                                                    <td>{{ stock.article }}</td>
                                                    <td>{{ stock.qte }}</td>
                                                    <td>{{ stock.qteReste }} </td>
                                                </tr>
                                            {% else %}
                                                <tr class="text-center">
                                                    <td colspan="3">{{ "no records found"|trans }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                       <br>
                                        <div class="text-right" >
                                            {{ knp_pagination_render(stocks) }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /content area -->
            </div>
            <!-- /main content -->

        </div>
        <!-- /page content -->
        {% include('layout/footer.html.twig') %}
    </div>
    <!-- /page container -->
    {#</div>
    </div>#}
{% endblock %}

templates/stock/search.html.twig
{% extends 'base.html.twig' %}

{# {% block title %} {{ app.user.email|upper }} {% endblock %} #}
{% block body_class %} class="nav-md" {% endblock %}
{% block body %}

    {#<div class="layout-boxed navbar-top">#}
    {% include('layout/navbar.html.twig') %}
    <!-- Page container -->
    <div class="page-container">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Page header -->
                <div class="col-md-12">
                    <div class="page-header page-header-default">
                        <div class="page-header-content">
                            <div class="page-title">

                            </div>
                        </div>
                        <div class="breadcrumb-line">
                            <ul class="breadcrumb">
                                <li><a href="#"><i class="icon-home2 position-left"></i> الملف</a></li>
                                <li class="active">المخزون</li>
                            </ul>

                        </div>
                    </div>
                </div>
                <!-- /page header -->
                <!-- Content area -->
                <div class="col-md-12">
                    <div class="panel">

                        <div class="col-md-12">
                            <div class="panel">
                                <div class="title">
                                    <h1> &nbsp;{{ "Print stock now"|trans }}&nbsp;&nbsp; </h1>

                                    <hr>
                                </div>
                                <div class="content">
                                    <div class="row">
            <fieldset>
            {{ form_start(form_search) }}

            <div class="col-lg-4">
                    <label class="col-lg-3 control-label">{{ "Categorie"|trans }}</label>

                    {{ form_widget(form_search.categorie,{'attr': {'class':'form-control col-lg-4'} }) }}
                </div>
                <div class="col-lg-4">
                    <label class="col-lg-3 control-label">{{ "Type"|trans }}</label>

                    {{ form_widget(form_search.type,{'attr': {'class':'form-control col-lg-4'} }) }}
                </div>
                <div class="col-lg-4">
                    <button class="btn btn-primary" type="submit" id="button-addon2"><i class="glyphicon glyphicon-print"></i>
                        {{ "print"|trans }} </button>
                </div>
                {{ form_end(form_search) }}
            </fieldset>
              <br>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /content area -->
                </div>
                <!-- /main content -->

            </div>
            <!-- /page content -->
            {% include('layout/footer.html.twig') %}
        </div>
        <!-- /page container -->
        
{% endblock %}

templates/stock/stockIni.html.twig
{% extends 'base.html.twig' %}

{# {% block title %} {{ app.user.email|upper }} {% endblock %} #}
{% block body_class %} class="nav-md" {% endblock %}
{% block body %}

    {#<div class="layout-boxed navbar-top">#}
    {% include('layout/navbar.html.twig') %}
    <!-- Page container -->
    <div class="page-container">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Page header -->
                <div class="col-md-12">
                    <div class="page-header page-header-default">
                        <div class="page-header-content">
                            <div class="page-title">

                            </div>
                        </div>
                        <div class="breadcrumb-line">
                            <ul class="breadcrumb">
                                <li><a href="#"><i class="icon-home2 position-left"></i> الملف</a></li>
                                <li class="active">المخزون</li>
                            </ul>

                        </div>
                    </div>
                </div>
                <!-- /page header -->
                <!-- Content area -->
                <div class="col-md-12">
                    <div class="panel">

                        <div class="col-md-12">
                            <div class="panel">
                                <div class="title">
                                    <h1> &nbsp;{{ "Stock initial"|trans }}&nbsp;&nbsp; </h1>

                                    <hr>
                                </div>
                                <div class="content">
                                    <div class="row">
                                        {# ------------filtrage ----------#}
                                        <form class="col-lg-3" role="search" methode="get">
                                            <div class="input-group lg-3">
                                                <input type="search" class="form-control" placeholder="اسم البضاعة" name="search">
                                                <div class="input-group-addon">
                                                    <button class="btn btn-primary" type="submit" id="button-addon2"><i class="glyphicon glyphicon-search"></i></button>
                                                </div>
                                            </div>
                                        </form>
                                        {#<form class="col-lg-3" role="search" methode="get">
                                            <div class="input-group lg-6">
                                                <div class="col-lg-6">
                                                    <input type="search" class="form-control" placeholder="اسم البضاعة" name="search">
                                                </div>
                                                <div class="col-lg-6">
                                                    <input type="search" class="form-control" placeholder="الصنف" name="search">
                                                </div>
                                                <div class="input-group-addon">
                                                    <button class="btn btn-primary" type="submit" id="button-addon2"><i class="glyphicon glyphicon-search"></i></button>
                                                </div>
                                            </div>
                                        </form>#}
                                        {#  <form class="col-lg-3" role="search" methode="get">
                                              <div class="input-group lg-3">
                                                  <div class="col-lg-6">
                                                      <input type="search" class="form-control" placeholder="الصنف" name="search">
                                                  </div>
                                                  <div class="col-lg-6">
                                                      <input type="search" class="form-control" placeholder="النوع" name="search">
                                                  </div>
                                                  <div class="input-group-addon">
                                                      <button class="btn btn-primary" type="submit" id="button-addon2"><i class="glyphicon glyphicon-search"></i></button>
                                                  </div>
                                              </div>
                                          </form>#}

                                        {# <div class="form-group">
                                         {{ form_start(form_search, {'attr': {'class': 'form-horizontal form-label-left'}}) }}

                                             <div class="col-lg-4">
                                                 {{ form_widget(form_search.categorie,{'attr': {'class':'form-control col-lg-6'} }) }}
                                             </div>
                                             <div class="col-lg-4">
                                                 {{ form_widget(form_search.type,{'attr': {'class':'form-control col-lg-6'} }) }}
                                             </div>

                                         <button class="btn btn-primary" type="submit" id="button-addon2"><i class="glyphicon glyphicon-search"></i>بحث</button>

                                         {{ form_end(form_search) }}
                                         </div>#}

                                        <table class="table table-bordered">
                                            <thead>
                                            <tr class="bg-orange-800">
                                                <th>{{ "Libele ar"|trans }}</th>
                                                <th>{{ "Categorie"|trans }}</th>
                                                <th>{{ "Type"|trans }}</th>
                                                <th>{{ "Qte ini"|trans }}</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for article in articles|sort|reverse %}
                                                <tr>
                                                    <td>{{ article.libele }}</td>
                                                    <td>{{ article.categorie }}</td>
                                                    <td>{{ article.type }}</td>
                                                    <td>{{ article.qteIni }}</td>

                                                </tr>
                                            {% else %}
                                                <tr class="text-center">
                                                    <td colspan="4">{{ "no records found"|trans }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                        <br>
                                        {#<div class="text-right" >
                                            {{ knp_pagination_render(articles) }}
                                        </div>#}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /content area -->
            </div>
            <!-- /main content -->

        </div>
        <!-- /page content -->
        {% include('layout/footer.html.twig') %}
    </div>
    <!-- /page container -->
    
{% endblock %}